spring:
  application:
    name: gulimall-member
  cloud:
    nacos:
      config:
        server-addr: 10.211.55.8:8848
        namespace: d0925224-a77e-4441-918b-bda7d609bc12
  config:
    import:
      - optional:nacos:datasource.yml?group=DEVELOP_GROUP
      - optional:nacos:mybatis-plus.yml?group=DEVELOP_GROUP
      - nacos:other.yml?group=DEVELOP_GROUP