spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      config:
        server-addr: 10.211.55.8:8848
        namespace: 7f2a71a8-d042-4bce-8465-6c7b50674888
  config:
    import:
      - optional:nacos:datasource.yml?group=DEVELOP_GROUP
      - optional:nacos:mybatis-plus.yml?group=DEVELOP_GROUP
      - nacos:other.yml?group=DEVELOP_GROUP